name: Feature
description: "Create a new feature request"
title: "[Feature]: "
labels: feature
body:
  - type: markdown
    attributes:
      value: |
        ## Description

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Provide a detailed description of the feature"
      placeholder: "Describe the feature here"
      value: "Describe the feature here"

  - type: markdown
    attributes:
      value: |
        ## Completion criteria

  - type: checkboxes
    id: done
    attributes:
      label: "The following should be done:"
      options:
        - label: Feature implemented
        - label: Unit tests added (if applicable)
        - label: Pull request opened
        - label: Pull request merged
